<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nishant1996" ignored="2" name="Default test(failed)" tests="1" failures="1" timestamp="2021-03-31T10:40:41 IST" time="0.047" errors="0">
  <testcase name="TC3" time="0.016" classname="ReRunfailedTests.sample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ReRunfailedTests.sample1.TC3(sample1.java:27)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase name="TC1" time="0.0" classname="ReRunfailedTests.sample1">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase name="TC2" time="0.0" classname="ReRunfailedTests.sample1">
    <ignored/>
  </testcase> <!-- TC2 -->
</testsuite> <!-- Default test(failed) -->
